<?php
/**
 * Copyright © 2020 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Frontend Options extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package Magenest_FrontendOptions
 *
 */

namespace Magenest\FrontendOptions\Block\Head;


use Magento\Framework\View\Element\Template;

class Library extends \Magento\Framework\View\Element\Template
{
    CONST LIBRARY_PATH_DEFAULT = 'magenest_frontend_options/library/';
    protected $_scopeConfig;


    public function __construct(Template\Context $context,
                                \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
                                array $data = [])
    {
        $this->_scopeConfig = $scopeConfig;
        parent::__construct($context, $data);
    }

    public function getConfigLibrary($libraryName)
    {
       return $this->_scopeConfig->getValue(self::LIBRARY_PATH_DEFAULT . $libraryName, \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
    }

    public function _toHtml()
    {
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }

}
