<?php
/**
 * Copyright © 2020 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * cf_theme extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package cf_theme
 * @package linhphung
 */
/** @var $block Magenest\FrontendOptions\Block\Head\Fonts
 */
$urlGoogleFront = $block->getGoogleFont();
$fontName = $block->getFontName();
?>
<?php if ($fontName && $urlGoogleFront): ?>
    <style>
        body {
            font-family: <?=$fontName?> !important;
        }
    </style>
    <link href="<?= $urlGoogleFront ?>" rel="stylesheet">
<?php endif; ?>
