<?php
/**
 * Copyright © 2020 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Frontend Options extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package Magenest_FrontendOptions
 *
 */
/** @var $block Magenest\FrontendOptions\Block\Head\Fonts
 */
$urlGoogleFront = $block->getGoogleFont();
$fontName = $block->getFontName();
$canApplyGoogleFont = $block->canApplyGoogleFont();
?>
<?php if ($fontName && $urlGoogleFront): ?>
    <link href="<?= $urlGoogleFront ?>" rel="stylesheet">
    <?php if ($canApplyGoogleFont): ?>
        <style>
            body {
                font-family: <?=$fontName?> !important;
            }
        </style>
    <?php endif; ?>
<?php endif; ?>
